#ifndef CODE_PET_INDICATOR_EXTENDER_H
#define CODE_PET_INDICATOR_EXTENDER_H

#include <Arduino.h>
#include <Wire.h>
#include <PCA95x5.h>

#define SPI_MISO 47
#define SPI_MOSI 48
#define SPI_SCLK 41

#define EXTENDER_SCL 40
#define EXTENDER_SDA 39
#define EXTENDER_INT 45
#define EXTENDER_SPEED 400000

#define EXPANDER_IO_RADIO_NSS PCA95x5::Port::P00
#define EXPANDER_IO_RADIO_RST PCA95x5::Port::P01
#define EXPANDER_IO_RADIO_BUSY PCA95x5::Port::P02
#define EXPANDER_IO_RADIO_DIO_1 PCA95x5::Port::P03

#define EXPANDER_IO_LCD_CS PCA95x5::Port::P04
#define EXPANDER_IO_LCD_RESET PCA95x5::Port::P05
#define EXPANDER_IO_LCD_INT PCA95x5::Port::P06
#define EXPANDER_IO_TP_RESET PCA95x5::Port::P07
#define EXPANDER_IO_RP2040_RESET PCA95x5::Port::P10
#define EXPANDER_IO_BMP_PWR PCA95x5::Port::P12

extern PCA9555 ioex;

void extender_init(void);

#endif
